name: Deploy Backend to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Build Backend Docker Image
      run: |
        docker build -t ecommerce-api ./api

    - name: Save Backend Docker Image
      run: |
        docker save ecommerce-api > ecommerce-api.tar

    - name: Decode SSH key
      run: |
      echo "${{ secrets.EC2_SSH_KEY }}" | base64 -d > folat.pem
      chmod 400 folat.pem

    - name: Upload files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
      host: ${{ secrets.EC2_HOST }}
      username: ubuntu
      key: folat.pem
      port: 22
      source: "./build"
      target: "/home/ubuntu/app"



    - name: Upload Image to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "ecommerce-api.tar"
        target: "/home/${{ secrets.EC2_USER }}/"

    - name: Deploy Backend on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker load < ecommerce-api.tar
          docker stop ecommerce-api || true
          docker rm ecommerce-api || true
          docker run -d --name ecommerce-api -p 80:3000 ecommerce-api

